### ISSUE TITLE
TypeError: fs.existsSync is not a function

### ISSUE THREAD

**Issue by nicoboy11** [gitana/gitana-javascript-driver#11]
I used the npm command to use Gitana driver on a React project (cloudcms main site links the React logo to the Javascript deriver documentation)

When I hit npm start on my React App it says: TypeError: fs.existsSync is not a function

Located at /node_modules/gitana/index.js line 28.

My Code: 

`import Gitana from 'gitana';

class App extends Component {

  callGitana() {
    Gitana.connect({
      "clientKey": "[myClientKey]",
      "clientSecret": "[myClientSecret]",
      "username": "[myUserName]",
      "password": "[myPassword]"
    }, function(err){
...`

**Comment by uzquiano** [comment]
Thanks for reporting this.

This was resolved in our 1.0.277 version of the driver.  The same NPM distribution now works for browser-based runtimes (React, Vue, Angular, etc) as well as server side Node.  

Going forward, we'll focus on NPM as a distribution mechanism for the driver and all dependency management.

If you run into any trouble with 1.0.277, feel free to drop us a line at support@cloudcms.com.

Cheers,

Michael
