### ISSUE TITLE
Older Version of gitana-javascript-driver contains injected malicious code

### ISSUE THREAD

**Issue by vhoudoverdov** [gitana/gitana-javascript-driver#16]
Greetings,

Version 1.0.143 of the gitana-javascript-driver located below contains a block of injected, obfuscated code.

URL:
http://code.cloudcms.com/gitana-javascript-driver/1.0.143/gitana.min.js

Reference:
![injected](https://user-images.githubusercontent.com/3037619/64462722-3d257100-d0b6-11e9-99ae-3134171f5026.JPG)

**Comment by uzquiano** [comment]
Hello,

Thanks for reporting this.  We have removed this.

We're looking through the others now.

Michael

**Comment by uzquiano** [comment]
Thank you once again.  I really appreciate the notification.
